In [ ]:
#1.Import numpy as np and see the version
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
#2. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
#matrix.
a=np.arange(1,11)
a
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#3. Create a numpy array containing the numbers from 1 to 20, and then extract the
#elements between the 5th and 15th index.
b=np.arange(1,21)
print(b)
b[5:16]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
#4. How to compute the mean, median, standard deviation of a numpy array?Use the array
#you created above
print('mean is',np.mean(b))
print('median is',np.median(b))
print('standard deviation  is',np.std(b))

mean is 10.5
median is 10.5
standard deviation  is 5.766281297335398


In [ ]:
#5. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
#shape (4,). Subtract y from each row of x using broadcasting.
x=np.array([[6,4,7,9],[12,5,9,4],[16,8,4,0]])
print(x)
y=np.array([4,8,12,16])
print(y)
result=x-y
print(result)

[[ 6  4  7  9]
 [12  5  9  4]
 [16  8  4  0]]
[ 4  8 12 16]
[[  2  -4  -5  -7]
 [  8  -3  -3 -12]
 [ 12   0  -8 -16]]
